# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/info/info.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'proto/info/info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/info/info.proto\x12\x08metadata\"\xa1\x01\n\x0cMetadataInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12 \n\x06\x62ucket\x18\x03 \x01(\x0e\x32\x10.metadata.Bucket\x12\x0c\n\x04path\x18\x04 \x01(\x0c\x12\x0c\n\x04size\x18\x05 \x01(\x04\x12\x0f\n\x07simhash\x18\x06 \x01(\x04\x12(\n\x08\x63hildren\x18\x07 \x03(\x0b\x32\x16.metadata.MetadataInfo*Y\n\x06\x42ucket\x12\x0c\n\x08\x44UMPSTER\x10\x00\x12\x0e\n\nLEAKS_LOGS\x10\x01\x12\x13\n\x0fLEAKS_DATABASES\x10\x02\x12\x10\n\x0c\x43OMBINATIONS\x10\x03\x12\n\n\x06PASTES\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.info.info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUCKET']._serialized_start=199
  _globals['_BUCKET']._serialized_end=288
  _globals['_METADATAINFO']._serialized_start=36
  _globals['_METADATAINFO']._serialized_end=197
# @@protoc_insertion_point(module_scope)
