// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.1
// source: proto/info/info.proto

package info_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bucket int32

const (
	Bucket_DUMPSTER        Bucket = 0
	Bucket_LEAKS_LOGS      Bucket = 1
	Bucket_LEAKS_DATABASES Bucket = 2
	Bucket_COMBINATIONS    Bucket = 3
	Bucket_PASTES          Bucket = 4
)

// Enum value maps for Bucket.
var (
	Bucket_name = map[int32]string{
		0: "DUMPSTER",
		1: "LEAKS_LOGS",
		2: "LEAKS_DATABASES",
		3: "COMBINATIONS",
		4: "PASTES",
	}
	Bucket_value = map[string]int32{
		"DUMPSTER":        0,
		"LEAKS_LOGS":      1,
		"LEAKS_DATABASES": 2,
		"COMBINATIONS":    3,
		"PASTES":          4,
	}
)

func (x Bucket) Enum() *Bucket {
	p := new(Bucket)
	*p = x
	return p
}

func (x Bucket) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bucket) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_info_info_proto_enumTypes[0].Descriptor()
}

func (Bucket) Type() protoreflect.EnumType {
	return &file_proto_info_info_proto_enumTypes[0]
}

func (x Bucket) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bucket.Descriptor instead.
func (Bucket) EnumDescriptor() ([]byte, []int) {
	return file_proto_info_info_proto_rawDescGZIP(), []int{0}
}

type MetadataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Bucket        Bucket                 `protobuf:"varint,3,opt,name=bucket,proto3,enum=metadata.Bucket" json:"bucket,omitempty"`
	Path          []byte                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Simhash       uint64                 `protobuf:"varint,6,opt,name=simhash,proto3" json:"simhash,omitempty"`
	Children      []*MetadataInfo        `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataInfo) Reset() {
	*x = MetadataInfo{}
	mi := &file_proto_info_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataInfo) ProtoMessage() {}

func (x *MetadataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_info_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataInfo.ProtoReflect.Descriptor instead.
func (*MetadataInfo) Descriptor() ([]byte, []int) {
	return file_proto_info_info_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MetadataInfo) GetBucket() Bucket {
	if x != nil {
		return x.Bucket
	}
	return Bucket_DUMPSTER
}

func (x *MetadataInfo) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *MetadataInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetadataInfo) GetSimhash() uint64 {
	if x != nil {
		return x.Simhash
	}
	return 0
}

func (x *MetadataInfo) GetChildren() []*MetadataInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_proto_info_info_proto protoreflect.FileDescriptor

var file_proto_info_info_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xd2, 0x01, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x69, 0x6d, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x69, 0x6d, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x32, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x2a, 0x59, 0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x0c, 0x0a, 0x08, 0x44, 0x55, 0x4d, 0x50, 0x53, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x4c, 0x45, 0x41, 0x4b, 0x53, 0x5f, 0x4c, 0x4f, 0x47, 0x53, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x4c, 0x45, 0x41, 0x4b, 0x53, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41, 0x53, 0x45,
	0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x4d, 0x42, 0x49, 0x4e, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x53, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x53, 0x54, 0x45, 0x53, 0x10,
	0x04, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_info_info_proto_rawDescOnce sync.Once
	file_proto_info_info_proto_rawDescData []byte
)

func file_proto_info_info_proto_rawDescGZIP() []byte {
	file_proto_info_info_proto_rawDescOnce.Do(func() {
		file_proto_info_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_info_info_proto_rawDesc), len(file_proto_info_info_proto_rawDesc)))
	})
	return file_proto_info_info_proto_rawDescData
}

var file_proto_info_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_info_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_info_info_proto_goTypes = []any{
	(Bucket)(0),          // 0: metadata.Bucket
	(*MetadataInfo)(nil), // 1: metadata.MetadataInfo
}
var file_proto_info_info_proto_depIdxs = []int32{
	0, // 0: metadata.MetadataInfo.bucket:type_name -> metadata.Bucket
	1, // 1: metadata.MetadataInfo.children:type_name -> metadata.MetadataInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_info_info_proto_init() }
func file_proto_info_info_proto_init() {
	if File_proto_info_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_info_info_proto_rawDesc), len(file_proto_info_info_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_info_info_proto_goTypes,
		DependencyIndexes: file_proto_info_info_proto_depIdxs,
		EnumInfos:         file_proto_info_info_proto_enumTypes,
		MessageInfos:      file_proto_info_info_proto_msgTypes,
	}.Build()
	File_proto_info_info_proto = out.File
	file_proto_info_info_proto_goTypes = nil
	file_proto_info_info_proto_depIdxs = nil
}
