# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/metadata/metadata.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/metadata/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/metadata/metadata.proto\x12\x08metadata\"D\n\x08Metadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x65mails\x18\x02 \x03(\x0c\x12\x0b\n\x03ips\x18\x03 \x03(\x0c\x12\x0f\n\x07\x64omains\x18\x04 \x03(\x0c\"1\n\x0cMetadataList\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.metadata.Metadatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.metadata.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATA']._serialized_start=43
  _globals['_METADATA']._serialized_end=111
  _globals['_METADATALIST']._serialized_start=113
  _globals['_METADATALIST']._serialized_end=162
# @@protoc_insertion_point(module_scope)
